version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb+srv://admin:SingleQuickNotes@cluster0.v5hhzmy.mongodb.net/tareas
volumes:
 mongodb:
